### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by CoreneMerchant** [puzzlemoondev/BililiveRecorder-webhook-docker#15]
⠼ webhook The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested  0.0s

不支持32位cpu？

**Comment by puzzlemoondev** [comment]
for now, we only build amd64 images.

**Comment by puzzlemoondev** [comment]
Multi arch is here. See [docker hub](https://hub.docker.com/r/puzzlemoondev/bililive-recorder-webhook)  for supported platforms.
