### ISSUE TITLE
 Service 'webhook' failed to build : Build failed

### ISSUE THREAD

**Issue by itgoyo** [puzzlemoondev/BililiveRecorder-webhook-docker#3]
国外机器ubuntu
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/23348551/215370265-ad17d3f0-db0b-4c3b-a1f1-c7f4acb2bfc8.png">

国内机器ubuntu，请问大佬有没有考虑proxy这种方式呢，就国内机器折腾代理还是有点麻烦的
<img width="1897" alt="image" src="https://user-images.githubusercontent.com/23348551/215372316-28daf104-9d60-4a56-af4c-62a08dd09c46.png">

docker compose up --detach，的时候出现了这个错误，请问这个只能`compose`么，直接run容器那种可以么？不太熟悉docker的基础原理，所以问一哈。

最后在自己的工作机`MacOS`上运行成功了，暂时不知道是什么问题，看错误的回答可能是云服务器内存不够，仍待考究

**Comment by puzzlemoondev** [comment]
你好，https://github.com/puzzlemoondev/BililiveRecorder-webhook-docker/commit/e0f89f30adbaf0f7f09dc34625d484f3190d1710 加了 `GOPROXY`，你可以试试。
`docker-compose` 只是把 `docker` 的指令包成设置文件方便部署，底下做的事情是一样的。

**Comment by itgoyo** [comment]
好嘞，感谢解答
