### ISSUE TITLE
关于webhook怎么查看状态呢？

### ISSUE THREAD

**Issue by itgoyo** [puzzlemoondev/BililiveRecorder-webhook-docker#4]
<img width="1658" alt="image" src="https://user-images.githubusercontent.com/23348551/215398340-91dc0e01-2603-409b-b810-ac7cef20c425.png">

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/23348551/215398171-a54519ba-1692-4054-bf38-612a6ea5f8f0.png">

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/23348551/215398231-459c282b-fa9d-4a75-bb42-e31272072433.png">

<img width="834" alt="image" src="https://user-images.githubusercontent.com/23348551/215398662-64f6351a-1144-4089-b6a4-34a69fb291da.png">

webhook v2：填写的地址`http://webhook:9999/hooks/recorder-file-closed`

我这边没用使用默认的9000端口改用了9999的端口,但是如图所示还是报错了，是我哪里设置错误了么？

**Comment by puzzlemoondev** [comment]
recorder的webhook认的是container里面的port。
https://github.com/puzzlemoondev/BililiveRecorder-webhook-docker/blob/e0f89f30adbaf0f7f09dc34625d484f3190d1710/compose.yml#L28
这里的mapping是`host:container`。
看你的截图，你改的是host的port没有改container的port。

**Comment by puzzlemoondev** [comment]
要改webhook在container内的端口记得加个`-port`的flag，见https://github.com/adnanh/webhook/blob/master/docs/Webhook-Parameters.md

然後改dockerfile expose的port
https://github.com/puzzlemoondev/BililiveRecorder-webhook-docker/blob/e0f89f30adbaf0f7f09dc34625d484f3190d1710/webhook.Dockerfile#L36

**Comment by itgoyo** [comment]
好的，感谢大佬的详细解答
